import 'package:flutter/material.dart';

enum SegmentInputMode {
  selectOnly,
  inputOnly,
  selectOrInput,
  autoGenerated,
  readOnly,
}

enum SegmentPopupType {
  none,
  list,
  tree,
  searchGrid,
}

enum SegmentValidationMode {
  none,
  regex,
  fixedLength,
  regexAndFixedLength,
}

class CompositeCodeSegmentDefinition {
  const CompositeCodeSegmentDefinition({
    required this.segmentKey,
    required this.label,
    required this.token,
    required this.inputMode,
    required this.popupType,
    required this.validationMode,
    this.fixedLength,
    this.regexPattern,
    this.required = false,
    this.dataSourceCode,
    this.displayStrategyCode,
    this.placeholder,
  });

  final String segmentKey;
  final String label;
  final String token;
  final SegmentInputMode inputMode;
  final SegmentPopupType popupType;
  final SegmentValidationMode validationMode;
  final int? fixedLength;
  final String? regexPattern;
  final bool required;
  final String? dataSourceCode;
  final String? displayStrategyCode;
  final String? placeholder;

  bool get allowsPopup =>
      popupType != SegmentPopupType.none &&
      (inputMode == SegmentInputMode.selectOnly ||
          inputMode == SegmentInputMode.selectOrInput);

  bool get allowsManualInput =>
      inputMode == SegmentInputMode.inputOnly ||
      inputMode == SegmentInputMode.selectOrInput;
}

class CompositeCodePatternDefinition {
  const CompositeCodePatternDefinition({
    required this.pattern,
    required this.separator,
    required this.segments,
  });

  final String pattern;
  final String? separator;
  final List<CompositeCodeSegmentDefinition> segments;
}

class CompositeCodeInputValue {
  const CompositeCodeInputValue({
    required this.finalCode,
    required this.segmentValues,
    required this.selectedObjects,
    required this.isValid,
    required this.validationErrors,
  });

  final String finalCode;
  final Map<String, String> segmentValues;
  final Map<String, dynamic> selectedObjects;
  final bool isValid;
  final Map<String, String> validationErrors;
}

class SegmentLookupItem {
  const SegmentLookupItem({
    required this.id,
    required this.code,
    required this.name,
    this.parentId,
    this.extraData,
  });

  final String id;
  final String code;
  final String name;
  final String? parentId;
  final Map<String, dynamic>? extraData;
}

abstract class SegmentDataSourceStrategy {
  Future<List<SegmentLookupItem>> search(
    String query,
    CompositeCodeSegmentDefinition segment,
  );

  Future<SegmentLookupItem?> findByCode(
    String code,
    CompositeCodeSegmentDefinition segment,
  );
}

class StaticListDataSourceStrategy extends SegmentDataSourceStrategy {
  StaticListDataSourceStrategy(this.itemsByDataSourceCode);

  final Map<String, List<SegmentLookupItem>> itemsByDataSourceCode;

  @override
  Future<List<SegmentLookupItem>> search(
    String query,
    CompositeCodeSegmentDefinition segment,
  ) async {
    final items = itemsByDataSourceCode[segment.dataSourceCode] ??
        const <SegmentLookupItem>[];
    final text = query.trim().toLowerCase();
    if (text.isEmpty) {
      return items;
    }

    return items.where((item) {
      return item.code.toLowerCase().contains(text) ||
          item.name.toLowerCase().contains(text);
    }).toList();
  }

  @override
  Future<SegmentLookupItem?> findByCode(
    String code,
    CompositeCodeSegmentDefinition segment,
  ) async {
    final items = itemsByDataSourceCode[segment.dataSourceCode] ??
        const <SegmentLookupItem>[];

    for (final item in items) {
      if (item.code.toLowerCase() == code.toLowerCase()) {
        return item;
      }
    }

    return null;
  }
}

class ApiDataSourceStrategy extends SegmentDataSourceStrategy {
  ApiDataSourceStrategy({
    required this.searchCallback,
    required this.findByCodeCallback,
  });

  final Future<List<SegmentLookupItem>> Function(
    String query,
    CompositeCodeSegmentDefinition segment,
  ) searchCallback;
  final Future<SegmentLookupItem?> Function(
    String code,
    CompositeCodeSegmentDefinition segment,
  ) findByCodeCallback;

  @override
  Future<List<SegmentLookupItem>> search(
    String query,
    CompositeCodeSegmentDefinition segment,
  ) {
    return searchCallback(query, segment);
  }

  @override
  Future<SegmentLookupItem?> findByCode(
    String code,
    CompositeCodeSegmentDefinition segment,
  ) {
    return findByCodeCallback(code, segment);
  }
}

class TreeDataSourceStrategy extends StaticListDataSourceStrategy {
  TreeDataSourceStrategy(super.itemsByDataSourceCode);
}

abstract class DisplayStrategy {
  String getDisplayText(SegmentLookupItem item);
}

class CodeOnlyDisplayStrategy extends DisplayStrategy {
  @override
  String getDisplayText(SegmentLookupItem item) {
    return item.code;
  }
}

class CodeNameDisplayStrategy extends DisplayStrategy {
  @override
  String getDisplayText(SegmentLookupItem item) {
    return '${item.code} - ${item.name}';
  }
}

class TreePathDisplayStrategy extends DisplayStrategy {
  TreePathDisplayStrategy({
    required this.items,
    this.separator = ' >> ',
  });

  final List<SegmentLookupItem> items;
  final String separator;

  @override
  String getDisplayText(SegmentLookupItem item) {
    final path = <String>[item.name];
    var parentId = item.parentId;

    while (parentId != null) {
      final parent = _findById(parentId);
      if (parent == null) {
        break;
      }
      path.insert(0, parent.name);
      parentId = parent.parentId;
    }

    return '${item.code} - ${path.join(separator)}';
  }

  SegmentLookupItem? _findById(String id) {
    for (final item in items) {
      if (item.id == id) {
        return item;
      }
    }
    return null;
  }
}

class PatternParser {
  static final RegExp _tokenExpression = RegExp(r'\{([^}]+)\}');

  static List<String> parsePatternTokens(String pattern) {
    return [
      for (final match in _tokenExpression.allMatches(pattern))
        match.group(1)!,
    ];
  }

  static CompositeCodeInputValue parseInput(
    String input,
    CompositeCodePatternDefinition definition,
  ) {
    final values = <String, String>{};
    final errors = <String, String>{};
    final separator = definition.separator;

    if (separator != null && separator.isNotEmpty) {
      final parts = input.split(separator);
      if (parts.length != definition.segments.length) {
        errors['_pattern'] = 'Input does not match the configured pattern.';
      }

      for (var i = 0; i < definition.segments.length; i++) {
        values[definition.segments[i].segmentKey] =
            i < parts.length ? parts[i] : '';
      }
    } else {
      var offset = 0;
      for (final segment in definition.segments) {
        final length = segment.fixedLength;
        if (length == null || length <= 0) {
          errors[segment.segmentKey] =
              'Fixed length is required when no separator is used.';
          values[segment.segmentKey] = '';
          continue;
        }

        final end = offset + length;
        values[segment.segmentKey] =
            input.length >= end ? input.substring(offset, end) : '';
        offset = end;
      }

      if (offset != input.length) {
        errors['_pattern'] = 'Input length does not match the configured pattern.';
      }
    }

    errors.addAll(validateSegments(values, definition));

    return CompositeCodeInputValue(
      finalCode: composeCode(values, definition),
      segmentValues: values,
      selectedObjects: const {},
      isValid: errors.isEmpty,
      validationErrors: errors,
    );
  }

  static String composeCode(
    Map<String, String> segmentValues,
    CompositeCodePatternDefinition definition,
  ) {
    var result = definition.pattern;

    for (final segment in definition.segments) {
      result = result.replaceAll(
        segment.token,
        segmentValues[segment.segmentKey] ?? '',
      );
    }

    return result;
  }

  static Map<String, String> validateSegments(
    Map<String, String> segmentValues,
    CompositeCodePatternDefinition definition,
  ) {
    final errors = <String, String>{};

    for (final segment in definition.segments) {
      final value = segmentValues[segment.segmentKey] ?? '';

      if (segment.required && value.trim().isEmpty) {
        errors[segment.segmentKey] = '${segment.label} is required.';
        continue;
      }

      if (value.isEmpty) {
        continue;
      }

      final checkFixedLength =
          segment.validationMode == SegmentValidationMode.fixedLength ||
              segment.validationMode == SegmentValidationMode.regexAndFixedLength;
      final checkRegex = segment.validationMode == SegmentValidationMode.regex ||
          segment.validationMode == SegmentValidationMode.regexAndFixedLength;

      if (checkFixedLength &&
          segment.fixedLength != null &&
          value.length != segment.fixedLength) {
        errors[segment.segmentKey] =
            '${segment.label} must be ${segment.fixedLength} characters.';
        continue;
      }

      if (checkRegex &&
          segment.regexPattern != null &&
          !RegExp(segment.regexPattern!).hasMatch(value)) {
        errors[segment.segmentKey] = '${segment.label} format is invalid.';
      }
    }

    return errors;
  }
}

class CompositeCodeInput extends StatefulWidget {
  const CompositeCodeInput({
    super.key,
    required this.definition,
    required this.onChanged,
    this.dataSourceStrategies = const <String, SegmentDataSourceStrategy>{},
    this.displayStrategies = const <String, DisplayStrategy>{},
    this.initialValue,
    this.labelText,
    this.helperText,
    this.enabled = true,
  });

  final CompositeCodePatternDefinition definition;
  final ValueChanged<CompositeCodeInputValue> onChanged;
  final Map<String, SegmentDataSourceStrategy> dataSourceStrategies;
  final Map<String, DisplayStrategy> displayStrategies;
  final String? initialValue;
  final String? labelText;
  final String? helperText;
  final bool enabled;

  @override
  State<CompositeCodeInput> createState() => _CompositeCodeInputState();
}

class _CompositeCodeInputState extends State<CompositeCodeInput> {
  late final TextEditingController _controller;
  Map<String, String> _segmentValues = <String, String>{};
  Map<String, dynamic> _selectedObjects = <String, dynamic>{};
  Map<String, String> _validationErrors = <String, String>{};

  @override
  void initState() {
    super.initState();
    _controller = TextEditingController(text: widget.initialValue ?? '');

    final initial = PatternParser.parseInput(
      widget.initialValue ?? '',
      widget.definition,
    );
    _segmentValues = Map<String, String>.from(initial.segmentValues);
    _validationErrors = Map<String, String>.from(initial.validationErrors);

    if ((widget.initialValue ?? '').isEmpty) {
      _applyAutoGeneratedSegments();
      _controller.text = PatternParser.composeCode(
        _segmentValues,
        widget.definition,
      );
      _validationErrors = PatternParser.validateSegments(
        _segmentValues,
        widget.definition,
      );
    }

    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (mounted) {
        _emitChanged();
      }
    });
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final errorText = _validationErrors.isEmpty
        ? null
        : _validationErrors.values.first;

    return TextFormField(
      controller: _controller,
      enabled: widget.enabled,
      readOnly: _allSegmentsReadOnly,
      decoration: InputDecoration(
        labelText: widget.labelText,
        helperText: widget.helperText,
        errorText: errorText,
        suffixIcon: IconButton(
          tooltip: 'Select segment',
          onPressed: widget.enabled ? _openSegmentPopupFromCursor : null,
          icon: const Icon(Icons.manage_search),
        ),
      ),
      onChanged: _handleManualInput,
    );
  }

  bool get _allSegmentsReadOnly {
    return widget.definition.segments.every((segment) {
      return segment.inputMode == SegmentInputMode.readOnly ||
          segment.inputMode == SegmentInputMode.autoGenerated ||
          segment.inputMode == SegmentInputMode.selectOnly;
    });
  }

  void _handleManualInput(String value) {
    final parsed = PatternParser.parseInput(value, widget.definition);
    final newValues = Map<String, String>.from(parsed.segmentValues);

    for (final segment in widget.definition.segments) {
      if (!segment.allowsManualInput) {
        newValues[segment.segmentKey] = _segmentValues[segment.segmentKey] ?? '';
      }
    }

    setState(() {
      _segmentValues = newValues;
      _applyAutoGeneratedSegments();
      _validationErrors = PatternParser.validateSegments(
        _segmentValues,
        widget.definition,
      );
      final recomposed = PatternParser.composeCode(
        _segmentValues,
        widget.definition,
      );
      if (recomposed != _controller.text) {
        _controller.value = TextEditingValue(
          text: recomposed,
          selection: TextSelection.collapsed(offset: recomposed.length),
        );
      }
    });
    _emitChanged();
  }

  void _applyAutoGeneratedSegments() {
    final now = DateTime.now();

    for (final segment in widget.definition.segments) {
      if (segment.inputMode != SegmentInputMode.autoGenerated) {
        continue;
      }

      switch (segment.token) {
        case '{YYYY}':
          _segmentValues[segment.segmentKey] = now.year.toString();
          break;
        case '{YY}':
          _segmentValues[segment.segmentKey] =
              now.year.toString().substring(2);
          break;
        case '{MM}':
          _segmentValues[segment.segmentKey] =
              now.month.toString().padLeft(2, '0');
          break;
        case '{DD}':
          _segmentValues[segment.segmentKey] =
              now.day.toString().padLeft(2, '0');
          break;
        default:
          _segmentValues.putIfAbsent(segment.segmentKey, () => '');
          break;
      }
    }
  }

  Future<void> _openSegmentPopupFromCursor() async {
    final selectableSegments = widget.definition.segments
        .where((segment) => segment.allowsPopup)
        .toList();
    if (selectableSegments.isEmpty) {
      return;
    }

    final cursorSegment = _segmentAtCursor();
    final segment = cursorSegment != null && cursorSegment.allowsPopup
        ? cursorSegment
        : selectableSegments.length == 1
            ? selectableSegments.first
            : await _chooseSegment(selectableSegments);

    if (segment == null) {
      return;
    }

    await _openLookupPopup(segment);
  }

  CompositeCodeSegmentDefinition? _segmentAtCursor() {
    final selectionOffset = _controller.selection.baseOffset;
    if (selectionOffset < 0) {
      return null;
    }

    var offset = 0;
    final separator = widget.definition.separator ?? '';

    for (var i = 0; i < widget.definition.segments.length; i++) {
      final segment = widget.definition.segments[i];
      final value = _segmentValues[segment.segmentKey] ?? '';
      final start = offset;
      final end = offset + value.length;
      if (selectionOffset >= start && selectionOffset <= end) {
        return segment;
      }
      offset = end + (i == widget.definition.segments.length - 1
          ? 0
          : separator.length);
    }

    return null;
  }

  Future<CompositeCodeSegmentDefinition?> _chooseSegment(
    List<CompositeCodeSegmentDefinition> segments,
  ) {
    return showDialog<CompositeCodeSegmentDefinition>(
      context: context,
      builder: (context) {
        return SimpleDialog(
          title: const Text('Select Segment'),
          children: [
            for (final segment in segments)
              SimpleDialogOption(
                onPressed: () => Navigator.of(context).pop(segment),
                child: Text(segment.label),
              ),
          ],
        );
      },
    );
  }

  Future<void> _openLookupPopup(
    CompositeCodeSegmentDefinition segment,
  ) async {
    final strategy = widget.dataSourceStrategies[segment.dataSourceCode];
    if (strategy == null) {
      setState(() {
        _validationErrors[segment.segmentKey] =
            'No data source configured for ${segment.label}.';
      });
      _emitChanged();
      return;
    }

    final selected = await showDialog<SegmentLookupItem>(
      context: context,
      builder: (context) {
        return _SegmentLookupDialog(
          segment: segment,
          strategy: strategy,
          displayStrategy: widget.displayStrategies[segment.displayStrategyCode] ??
              CodeNameDisplayStrategy(),
        );
      },
    );

    if (selected == null) {
      return;
    }

    setState(() {
      _segmentValues[segment.segmentKey] = selected.code;
      _selectedObjects[segment.segmentKey] = selected;
      _validationErrors = PatternParser.validateSegments(
        _segmentValues,
        widget.definition,
      );
      _controller.text = PatternParser.composeCode(
        _segmentValues,
        widget.definition,
      );
    });
    _emitChanged();
  }

  void _emitChanged() {
    final finalCode = PatternParser.composeCode(_segmentValues, widget.definition);
    widget.onChanged(
      CompositeCodeInputValue(
        finalCode: finalCode,
        segmentValues: Map<String, String>.from(_segmentValues),
        selectedObjects: Map<String, dynamic>.from(_selectedObjects),
        isValid: _validationErrors.isEmpty,
        validationErrors: Map<String, String>.from(_validationErrors),
      ),
    );
  }
}

class _SegmentLookupDialog extends StatefulWidget {
  const _SegmentLookupDialog({
    required this.segment,
    required this.strategy,
    required this.displayStrategy,
  });

  final CompositeCodeSegmentDefinition segment;
  final SegmentDataSourceStrategy strategy;
  final DisplayStrategy displayStrategy;

  @override
  State<_SegmentLookupDialog> createState() => _SegmentLookupDialogState();
}

class _SegmentLookupDialogState extends State<_SegmentLookupDialog> {
  final TextEditingController _searchController = TextEditingController();
  List<SegmentLookupItem> _items = const <SegmentLookupItem>[];
  bool _loading = true;

  @override
  void initState() {
    super.initState();
    _search('');
  }

  @override
  void dispose() {
    _searchController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final title = switch (widget.segment.popupType) {
      SegmentPopupType.list => 'Select ${widget.segment.label}',
      SegmentPopupType.tree => 'Browse ${widget.segment.label}',
      SegmentPopupType.searchGrid => 'Search ${widget.segment.label}',
      SegmentPopupType.none => 'Select ${widget.segment.label}',
    };

    return AlertDialog(
      title: Text(title),
      content: SizedBox(
        width: 520,
        height: 420,
        child: Column(
          children: [
            TextField(
              controller: _searchController,
              decoration: const InputDecoration(
                hintText: 'Search',
                prefixIcon: Icon(Icons.search),
              ),
              onChanged: _search,
            ),
            const SizedBox(height: 8),
            Expanded(
              child: _loading
                  ? const Center(child: CircularProgressIndicator())
                  : ListView.separated(
                      itemCount: _items.length,
                      separatorBuilder: (_, __) => const Divider(height: 1),
                      itemBuilder: (context, index) {
                        final item = _items[index];
                        return ListTile(
                          dense: widget.segment.popupType !=
                              SegmentPopupType.searchGrid,
                          leading: Icon(_iconForPopupType(widget.segment.popupType)),
                          title: Text(widget.displayStrategy.getDisplayText(item)),
                          subtitle: widget.segment.popupType ==
                                  SegmentPopupType.searchGrid
                              ? Text(item.id)
                              : null,
                          onTap: () => Navigator.of(context).pop(item),
                        );
                      },
                    ),
            ),
          ],
        ),
      ),
      actions: [
        TextButton(
          onPressed: () => Navigator.of(context).pop(),
          child: const Text('Cancel'),
        ),
      ],
    );
  }

  Future<void> _search(String query) async {
    setState(() => _loading = true);
    final items = await widget.strategy.search(query, widget.segment);
    if (!mounted) {
      return;
    }

    setState(() {
      _items = items;
      _loading = false;
    });
  }

  IconData _iconForPopupType(SegmentPopupType popupType) {
    switch (popupType) {
      case SegmentPopupType.none:
        return Icons.radio_button_unchecked;
      case SegmentPopupType.list:
        return Icons.list_alt;
      case SegmentPopupType.tree:
        return Icons.account_tree_outlined;
      case SegmentPopupType.searchGrid:
        return Icons.grid_on;
    }
  }
}
